-- Apply in the Supabase SQL Editor. Ordinary SQL tables only; no stored functions.
-- Four tables: three core + the optional in-app alerts bonus.
-- For a clean setup, use a new Supabase project.
create table if not exists tracked_products (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  store_url text not null unique,
  last_price numeric(12,2),
  last_currency text,
  last_in_stock boolean,
  last_scraped_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists price_history (
  id bigint generated by default as identity primary key,
  product_id uuid not null references tracked_products(id) on delete cascade,
  price numeric(12,2) not null check (price >= 0),
  currency text not null,
  in_stock boolean not null,
  scraped_at timestamptz not null default now()
);

create table if not exists scrape_logs (
  id bigint generated by default as identity primary key,
  product_id uuid not null references tracked_products(id) on delete cascade,
  attempted_at timestamptz not null default now(),
  attempt_no integer not null check (attempt_no >= 1),
  outcome text not null check (outcome in ('success', 'retried', 'failed')),
  duration_ms integer not null check (duration_ms >= 0),
  error_message text
);

create table if not exists alerts (
  id bigint generated by default as identity primary key,
  product_id uuid not null references tracked_products(id) on delete cascade,
  kind text not null check (kind in ('price_drop', 'back_in_stock')),
  message text not null,
  created_at timestamptz not null default now()
);

create index if not exists history_by_product on price_history(product_id, scraped_at desc);
create index if not exists logs_by_product on scrape_logs(product_id, attempted_at desc);
create index if not exists alerts_by_product on alerts(product_id, created_at desc);

-- The browser never uses the database service key; only the Express backend does.
alter table tracked_products enable row level security;
alter table price_history enable row level security;
alter table scrape_logs enable row level security;
alter table alerts enable row level security;


-- Express uses the Supabase service-role key on the backend only.
-- No anonymous or public table policies are created. Do not expose this key to React.
